config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :article_versions, path: :versions, only: [:show, :new, :create, :edit, :update], as: :versions
  end

  resources :sessions, only: [:new, :create]
  resources :users, except: [:index, :edit, :update]

  get 'search' => 'articles#search'
  delete 'sessions', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :versions, class_name: "ArticleVersion"
  accepts_nested_attributes_for :versions

  validates_presence_of :versions

  def latest_version
    versions.order("updated_at").last
  end

  def latest_saved_version
    versions.order("updated_at").select { |version| !version.is_draft }.last
  end

  def first_version
    versions.order("created_at").first
  end

  def prior_versions
    versions.order("updated_at")[0..-2]
  end

  def ordered_saved_versions
    versions.order(created_at: :desc).select {|version| !version.is_draft}
  end

  def self.featured
    self.where(is_featured: true).order(updated_at: :desc)
  end

  def self.search(param, articles = self.all)
    articles.select { |article| article.latest_version.title.downcase.include? param.downcase}
  end

  def self.with_a_saved_version
    self.select { |article| article.latest_saved_version }
  end

  def self.search_saved_versions(param)
    self.search(param, self.with_a_saved_version)
  end
end

app/models/article_version.rb
class ArticleVersion < ApplicationRecord
  belongs_to :article
  belongs_to :author, class_name: "User"

  validates_presence_of :content, :author, :article, :title

end

app/models/user.rb
class User < ApplicationRecord
  has_many :article_versions, foreign_key: :author_id
  belongs_to :type, class_name: "UserType"
  has_many :contributed_articles, through: :article_versions, source: :article
  has_secure_password

  validates_presence_of :username
  validates_uniqueness_of :username

  def saved_version_drafts
    article_versions.select { |version| version.is_draft == true }
  end

  def articles_originally_created
    article_versions.select { |version| version.article.first_version.author == self }
  end

  def promote_to_admin_if_ready
    if type.name.downcase != "admin" && articles_originally_created.count >= 10
      self.type = UserType.find_or_create_by(name: "admin")
      self.save
    end
  end

  def is_admin?
    type.name.downcase == "admin"
  end
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users, foreign_key: :type_id

  def self.anything_but_admin
    self.all.select {|type| type unless type.name.downcase == "admin" }.first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/article_versions_controller.rb
class ArticleVersionsController < ApplicationController
  before_action :authenticate!, only: [:create, :update]
  before_action :get_version, only: [:show, :edit, :update]
  before_action :get_article, only: [:show, :create]

  def show
    p params
    p @article_version
    p '*' * 50
    p @article_version.author
    if @article_version.is_draft && @article_version.author == current_user
      redirect_to current_user
    elsif @article_version.is_draft
      not_found
    end
  end

  def create
    @article_version = ArticleVersion.new(article: @article,
                                          author: current_user,
                                          content: @article.latest_saved_version.content,
                                          title: @article.latest_saved_version.title
                                          )
    if authorized?(@article.first_version.author) && @article_version.save
      redirect_to edit_article_version_path(@article_version.article, @article_version)
    else
      @article_version = @article.latest_saved_version
      @error_message = "You aren't authorized to contribute to this."
      render 'show'
    end
  end

  def edit
  end

  def update
    if @article_version.update(version_params)
      redirect_to article_version_path(@article_version.article, @article_version)
    else
      render 'edit'
    end
  end

  private
  def get_version
    @article_version = ArticleVersion.find(params[:id])
  end

  def get_article
    @article = Article.find(params[:article_id])
  end

  def version_params
    params.require(:article_version).permit(:content, :is_draft, :title)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate!, only: [:new, :create, :update]
  before_action :get_article, only: [:show, :edit, :update]

  def index
    @featured_articles = Article.featured
  end

  def show
    redirect_to article_version_path(@article, @article.latest_saved_version)
  end

  def search
    @search_param = params[:q]
    @search_results = Article.search_saved_versions(@search_param)
    render :search
  end

  def new
    @article = Article.new
    @article.versions.build
  end

  def create
    @article = Article.new(article_params)
    @article.versions.first.author = current_user

    if @article.save
      current_user.promote_to_admin_if_ready
      redirect_to article_version_path(@article, @article.latest_version)
    else
      render 'new'
    end
  end

  def update
    if @article.latest_saved_version && @article.update(article_params)
      redirect_back(fallback_location: root_path)
    else
      redirect_to root_path
    end
  end

  private
  def article_params
    params.require(:article).permit(:is_featured, versions_attributes: [:content, :is_draft, :title])
  end

  def get_article
    @article = Article.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user == @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      @error_message = "invalid username/password combo"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate!, only: [:show]
  before_action :get_user, only: [:show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.merge(type: UserType.find_or_create_by(name: "contributor")))
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end
  private
    def user_params
      params.require(:user).permit(:username, :password)
    end

    def get_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def authenticate!
    redirect_to new_session_path unless logged_in?
  end

  def user_is_admin?
    current_user.is_admin? if logged_in?
  end

  def authorized?(user)
    current_user.is_admin? || current_user == user
  end
end

app/views/article_controllers/edit.html.erb
<h1>Edit Draft</h1>

<%= form_with id: "new-article", model: @ , local: true do |form| %>
  <p>
    <%= form.label :title, "Enter the title of your article" %>
    <%= form.text_field :title %>
  </p>

  <%= form.fields_for :versions do |field| %>
    <p>
      <%= field.label :content, "Enter the content of your article" %>
      <%= field.cktext_area :content %>
    </p>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/article_versions/edit.html.erb
<h1>Edit Article</h1>

<%= form_with id: "edit-article-version", url: article_version_url(@article_version.article, @article_version), method: "patch", local: true do |form| %>
  <% if @article_version.errors.any? %>
    <p>
      <%= pluralize(@article_version.errors.count, "error") %> prohibited this article_version from being saved.
    </p>
    <ul>
      <% @article_version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form.fields_for :article_version do |field| %>
    <p>
      <%= field.label :title, "Enter the title of your article" %>
      <%= field.text_area :title, value: @article_version.title %>
      <%= field.label :content, "Enter the content of your article" %>
      <%= field.cktext_area :content, value: @article_version.content %>
    </p>
    <p>
      <%= field.label :is_draft, "Check the box to save as as a draft." %>
      <%= field.check_box :is_draft %>
    </p>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/article_versions/show.html.erb
<h2><%= @article_version.title %></h2>

<div id="featured-article">
  <% if @article.is_featured %>
    <h4><em>Featured Article</em></h4>
    <% if user_is_admin? %>
      <%= form_tag @article, method: "patch" do %>
        <%= hidden_field_tag :"article[is_featured]", false %>
        <%= submit_tag "Unfeature this article" %>
      <% end %>
    <% end %>
  <% elsif user_is_admin? %>
      <%= form_tag @article, method: "patch" do %>
        <%= hidden_field_tag :"article[is_featured]", true %>
        <%= submit_tag "Feature this article" %>
      <% end %>
  <% end %>
</div>

<article class="article-content">
  <p>
    <%= @article_version.content.html_safe %>
  </p>
  <small>-Written by: <%= link_to "#{@article_version.author.username}", @article_version.author, class: "username-link"%> on <%=  @article_version.updated_at.strftime('%c') %></small>
</article>

<p><%= link_to "Contribute to this article", article_versions_path(@article), method: 'post' %>
<% if @error_message %>
  <ul>
    <li><%= @error_message %></li>
  </ul>
<% end %>

<div class="version-container">
  <h5>Time Machine:</h5>
  <ul>
    <% @article.ordered_saved_versions.each do |version| %>
      <% if version == @article_version %>
        <li class="shown-version"><small><i><%= version.title %></i><br> by: <%= link_to "#{version.author.username}", version.author, class: "username-link"%> written on <%= version.created_at.strftime('%c') %></small></li>

      <% else %>
       <li class="version-links"><small><i><%= link_to "#{version.title}", article_version_path(@article, version) %></i><br> by: <%= link_to "#{version.author.username}", version.author, class: "username-link" %> written on <%= version.created_at.strftime('%c') %></small></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/articles/index.html.erb
<div class='search-box'>
<h3>Search</h3>

<%= form_tag("/search", method: "get") do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Chill") %>
<% end %>
</div>
<div class="new-article">
<%= button_to "Create a New Article", new_article_path, :method => :get %>
</div>
<div class="featured-articles">
  <h2>Featured Articles</h2>
  <% if @featured_articles.any? %>
    <% @featured_articles.each do |article| %>
      <div class="version-links featured-article"><%= link_to "#{article.latest_saved_version.title}", article_version_path(article, article.latest_saved_version), class: "title-link" %> <br>by: <%= link_to "#{article.latest_saved_version.author.username}", article.latest_saved_version.author, class: "username-link" %> written on <%= article.latest_saved_version.updated_at.strftime('%c') %>
      <% if user_is_admin? %>
        <%= form_tag article, method: "patch" do %>
          <%= hidden_field_tag :"article[is_featured]", false %>
          <%= submit_tag "Unfeature this article" %>
        <% end %>
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<% if @article.errors.any? %>
  <p>
    <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved.
  </p>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with id: "new-article", model: @article, local: true do |form| %>

  <%= form.fields_for :versions do |field| %>
    <p>
      <%= field.label :title, "Enter the title of your article" %>
      <%= field.text_field :title %>
      <%= field.label :content, "Enter the content of your article" %>
      <%= field.cktext_area :content %>
    </p>
    <p>
      <%= field.label :is_draft, "Check the box to save as as a draft." %>
      <%= field.check_box :is_draft %>
    </p>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/articles/search.html.erb
<h2>Search Results</h2>
<div class='featured-articles'>
<% if @search_results.any? %>
    <% @search_results.each do |article| %>
      <div class='version-links featured-article'><%= link_to "#{article.latest_saved_version.title}", article_version_path(article, article.latest_saved_version), class: "title-link" %> <br> Latest update by: <%= link_to "#{article.latest_saved_version.author.username}", article.latest_saved_version.author, class: "username-link" %> on <%= article.latest_saved_version.created_at.strftime('%c') %></div>
    <% end %>
<% else %>
</div>
  <h3>Sorry! We couldn't find any posts that match <%= @search_param %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChillOutt</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <main class="container">
      <h1 class="page-title">Chill Outt. . .</h1>
      <nav id="main-menu">
        <div id="nav-container">
          <% if logged_in? %>
            <span><%= link_to "#{current_user.username}", current_user %> | <%= link_to "logout", logout_path, method: :delete %></span>
          <% else %>
            <span><%= link_to "login", new_session_path %> | <%= link_to "register", new_user_path %></span>
          <% end %>
            <span> | <%= link_to "home", root_path %></span>
        </div>
      </nav>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<h1>register yoself</h1>

<%= form_with(id: "new-user", model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <p>
      <%= pluralize(@user.errors.count, "error") %> prohibited this user from being registered.
    </p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h2 class="user-title"><%= @user.username %></h2>

<% if @user == current_user %>
  <h3>Saved Drafts</h3>

  <div id="draft-list">
    <% @user.saved_version_drafts.each do |version| %>
      <p><%= link_to "#{version.title}", edit_article_version_path(version.article, version) %></p>
      <small>Last saved: <%=  version.updated_at.strftime('%c') %></small>
    <% end %>
  </div>
<% end %>

<% if @user.articles_originally_created %>
  <h3>Contributed Articles</h3>

  <% @user.contributed_articles.uniq.each do |article| %>
    <% if article.latest_saved_version %>
      <div class="version-links featured-article"><%= link_to "#{article.latest_saved_version.title}", article_version_path(article, article.latest_saved_version), class: "title-link" %> <br>Latest update by: <%= link_to "#{article.latest_saved_version.author.username}", article.latest_saved_version.author, class: "username-link" %> written on <%= article.latest_saved_version.updated_at.strftime('%c') %>
      </div>
    <% end %>
  <% end %>
<% end %>